name: cat_facts
description: Funny cat facts

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # for being able to compare objects in Dart
  equatable: ^2.0.5

  # for API communication
  retrofit: ^3.3.1
  dio: ^4.0.6

  # for logging purpose
  logger: ^1.1.0

  # for storing data on the device
  hive: ^2.2.3

  path_provider: ^2.0.11

  # for localization
  intl: ^0.17.0

  google_fonts: ^3.0.1

  # for toasting messages
  fluttertoast: ^8.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # for easy creating launcher icons
  flutter_launcher_icons: ^0.11.0
  # for type conversion dio client generator
  retrofit_generator: ^4.2.0
  # for generating files
  build_runner: ^2.3.2
  #for handling JSON
  json_serializable: ^6.5.4
  # for hive files
  hive_generator: ^2.0.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true
